#1. What is a Python library? Why do we use Python libraries?

Ans : Python library is a collection of function that allows you to perform many tasks without writing the code from scratch.

Python library is used to save time and effort,becuase we dont have to write the code from scratch and reusability of code also help to save time and effort.
**bold text**
Python library increase productivity and efficiency.


#2. What is the difference between Numpy array and List?

Ans :

Numpy array ->

1. Numpy array has faster computational speed.  
2. Numpy array can store same datatype elements only.
3. Numpy array can retrieve data faster as it stores elements based on indezes.  


List ->

1. List has slower computational speed.  
2. List can store multiples datatypes elements.
3. List does not store themselves they store address of memory location.



# 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [8]:
import numpy as np
arr = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8], [9, 10, 11, 12]])

In [9]:
arr.shape

(3, 4)

In [10]:
arr.size

12

In [11]:
arr.ndim

2

# 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
arr = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8], [9, 10, 11, 12]])

In [13]:
arr[0]

array([1, 2, 3, 4])

# 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [14]:
arr = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8], [9, 10, 11, 12]])

In [19]:
arr[2,3]

12

# 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [20]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [23]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
arr.flatten()[1::2]

array([ 2,  4,  6,  8, 10, 12])

# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [27]:
arr = np.random.random_sample((3,3))

In [31]:
arr

array([[0.64481485, 0.81847238, 0.4589448 ],
       [0.35546707, 0.87420303, 0.25027256],
       [0.81472312, 0.67330139, 0.35964067]])

# 8. Describe the difference between np.random.rand and np.random.randn?

Ans :

np.random.rand ->

This function is used to generate random numbers from a uniform distribution between [0,1) where 0 is inclusive and 1 is exclusive.


np.random.randn ->

This function is used to generate random numbers from a normal distribution.

# 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [32]:
arr = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8], [9, 10, 11, 12]])

In [33]:
np.expand_dims(arr , axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

# 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [34]:
arr = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8], [9, 10, 11, 12]])

In [35]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# 11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python


1. Index wise multiplication
2. Matrix multiplication  
3. Add both the matrics  
4. Subtract matrix B from A
5. Divide Matrix B by A  



In [37]:
arr1 = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [38]:
# Indexwise multuplication
arr1 + arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [41]:
# Matrix multiplication
arr1 @ arr2.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [42]:
# Add both the matrics
np.add(arr1,arr2)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [43]:
# Subtract matrix B from A
arr2 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [44]:
# Divide Matrix B by A
arr2 / arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 12. Which function in Numpy can be used to swap the byte order of an array?

Ans : The byteswap() function in numpy is used to swap the byte order of an array.

# 13. What is the significance of the np.linalg.inv function?

Ans : The np.linalg.inv fucntion in Numpy used to compute the inverse of a given square matrix.

The significance of this function is the ability to solve linear equations , matrix division, etc.

# 14. What does the np.reshape function do, and how is it used?

Ans :  

The np.reshape() function is used to change the shape of an array without changing its data.

It is used to change the shape but the shape should be multiple of size.


In [45]:
arr = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

In [46]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
arr.size

12

In [48]:
arr.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# 15. What is broadcasting in Numpy?

Ans : Broadcasting in Numpy is the ability to perform arithmetic operation on arrays of different shapes.

In [50]:
# Example
arr = np.array([[1,2,3],[4,5,6]])

In [51]:
arr + [1,2,3]

array([[2, 4, 6],
       [5, 7, 9]])